spring:
  datasource:
    url: jdbc:h2:mem:accounts_db;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS accounts_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
  h2:
    console:
      enabled: true
server:
  port: 8081



